// Type shim for the generated verdict lists. The JSON itself is generated by
// `src-tauri/src/backend/verdict_gen.rs` (`REGEN_HUB_VERDICTS=1 cargo test -p
// claude-fleet --lib verdict_gen`) from the one table
// (`src-tauri/src/backend/verdicts.rs`) the backend enforces from. Vite/
// Vitest load the JSON natively; this file only gives svelte-check a type for
// the import without enabling `resolveJsonModule` project-wide — see
// `names.json.d.ts` for the same trick.
declare const verdicts: {
  readonly local_only: readonly string[];
  readonly routed: readonly string[];
  readonly routed_unless: readonly { readonly command: string; readonly unless: string }[];
  readonly same_in_both: readonly string[];
};
export default verdicts;
