// The Svelte kit's stylesheet, `of.generated.css`, is the design manual's
// component CSS (`design-system/components/bundle.css`) verbatim: everything
// before its AI section (AISuggestion lands in step 3.11) plus its
// reduced-motion rule. The loaders in between are the loader kit's
// (loader-kit-extract.ts). `kit.test.ts` fails when the two drift;
// regenerate with
//   REGEN_KIT=1 pnpm exec vitest run src/lib/kit/kit.test.ts
// (the run writes the file, then fails on purpose: read the diff, run again).

export function kitCss(bundle: string): string {
  const end = bundle.indexOf('/* AI */');
  const reduced = bundle.match(/@media \(prefers-reduced-motion: reduce\)\{\.of \*\{[^}]*\}\}/);
  if (end < 0 || !reduced) throw new Error('bundle.css: kit section markers not found');
  return (
    "/* GENERATED by src/lib/kit/kit-extract.ts from the design manual's bundle.css.\n" +
    ' * Do not edit; regenerate with\n' +
    ' *   REGEN_KIT=1 pnpm exec vitest run src/lib/kit/kit.test.ts */\n' +
    bundle.slice(0, end).trimEnd() +
    '\n' +
    reduced[0] +
    '\n'
  );
}
