// Test support for the generated pages: an `invoke` router that answers from
// `registry.generated.json` — exactly what `list_pages` and
// `describe_fleet_settings` return on a fresh store (regenerated by
// `REGEN_PAGE_DOCS=1 cargo fleet-test -- page_docs_are_current`) — so
// every renderer test runs against the real pages and the real registry.
// Imported by tests only.
import registry from './registry.generated.json';
import type { Descriptor, PagesBundle } from './pages';

export const bundle = {
  pages: registry.pages,
  sources: registry.sources,
  resources: registry.resources,
  actions: registry.actions,
} as unknown as PagesBundle;
export const allDescriptors = registry.descriptors as unknown as Descriptor[];

export function descriptorOf(key: string): Descriptor {
  const d = allDescriptors.find((x) => x.key === key);
  if (!d) throw new Error(`no descriptor for ${key}`);
  return d;
}

/** What each data source answers in tests. */
export const SOURCE_DATA: Record<string, unknown> = {
  'usage.total': {
    input_tokens: 1_500_000,
    output_tokens: 42_000,
    cache_write_tokens: 0,
    cache_read_tokens: 0,
    cost_micros: 12_340_000,
  },
  'usage.by_day': [
    { day: '2026-09-26', cost_micros: 2_000_000, input_tokens: 10, output_tokens: 1 },
    { day: '2026-09-27', cost_micros: 5_000_000, input_tokens: 20, output_tokens: 2 },
  ],
  'usage.by_host': [{ host: 'alpha', input_tokens: 10, output_tokens: 1, cost_micros: 300 }],
  'work.retention': [
    { kept: 'Work journal', days: 365, rows: 40, would_delete: 3 },
    { kept: 'Done tickets', days: 0, rows: 12, would_delete: 0 },
    { kept: 'Work timeline', days: 90, rows: 500, would_delete: 120 },
  ],
  'work.retention_last': { at: null, journal: 0, tracker_items: 0, timeline_work_events: 0, tracker_writes: 0, describe_cache: 0 },
  'work.usage': [
    { group: 'links', counted: '3 made (manual 3)' },
    { group: 'trackers', counted: 'none' },
  ],
  'decide.today': {
    input_tokens: 41_000,
    budget: 2_000_000,
    cost_micros: 860,
    breaker: 'closed',
    key: 'set',
    orgs_allowed: 'Acme',
  },
  'usage.by_model': [
    { model: 'claude-opus-5', sessions: 2, input_tokens: 20, output_tokens: 0, cost_micros: 3_000_000 },
  ],
};

/**
 * An `invoke` implementation over a live settings map: reads answer from it,
 * `set_fleet_setting` writes it (refusing a read-only key and an out-of-range
 * number the way the backend does) and returns the whole map. Anything else
 * goes to `fallback`.
 */
export function registryRouter(
  initial: Record<string, string> = {},
  fallback: (cmd: string, args?: unknown) => unknown = () => null,
) {
  const values: Record<string, string> = Object.fromEntries(
    allDescriptors.map((d) => [d.key, d.value]),
  );
  Object.assign(values, initial);
  const impl = async (cmd: string, args?: unknown): Promise<unknown> => {
    switch (cmd) {
      case 'list_pages':
        return bundle;
      case 'describe_fleet_settings':
        return allDescriptors.map((d) => ({ ...d, value: values[d.key], modified: values[d.key] !== d.default }));
      case 'get_fleet_settings':
        return { ...values };
      case 'set_fleet_setting': {
        const { key, value } = args as { key: string; value: string };
        const d = allDescriptors.find((x) => x.key === key);
        if (!d) throw { code: 'E_INVALID', message: `unknown setting ${key}` };
        if (d.owned_by) throw { code: 'E_INVALID', message: `${key} is read-only here` };
        if (d.kind.type === 'int' && !(Number(value) >= d.kind.min && Number(value) <= d.kind.max)) {
          throw {
            code: 'E_INVALID',
            message: `${key} must be an integer between ${d.kind.min} and ${d.kind.max}`,
          };
        }
        values[key] = value;
        return { ...values };
      }
      case 'fetch_page_source': {
        const { id } = args as { id: string };
        if (!(id in SOURCE_DATA)) throw { code: 'E_INVALID', message: `unknown data source ${id}` };
        return SOURCE_DATA[id];
      }
      default:
        return fallback(cmd, args);
    }
  };
  return { impl, values };
}

/** Open one of a record editor's tabs (the org's Overview, Members,
 *  Devices, Spend, Settings) once it is drawn. */
export async function openRecordTab(name: string): Promise<void> {
  const { waitFor, fireEvent } = await import('@testing-library/svelte');
  const tab = await waitFor(() => {
    const el = document.querySelector<HTMLElement>(`[data-testid="record-tabs"] [data-tab="${name}"]`);
    if (!el) throw new Error(`no ${name} tab`);
    return el;
  });
  await fireEvent.click(tab);
}
