//! Whose words a submitted prompt is: the person's, or Claude Code's own.
//!
//! The UserPromptSubmit hook sees every user turn, and Claude Code submits
//! some of them itself: a background task finishing (`<task-notification>`),
//! a slash command's echo and output (`<command-name>`,
//! `<local-command-stdout>`), a `!` bash line (`<bash-input>`), a reminder
//! (`<system-reminder>`). None of them is something a person typed, so none
//! may be a conversation's first prompt, a work-detection signal, a census
//! text or a benchmark case. [`human_part`] is the one test all of them use
//! (through `work::detect::loop_guard`, which the census and the J1
//! benchmark call via `FleetPrompts`).
//!
//! The rule follows `transcript::parse_conversation`: a harness block is
//! recognised only at the HEAD of the prompt, so a person who pastes a
//! transcript or mentions a tag keeps their prompt.

/// Tags Claude Code opens a user turn with. A block of one of these that is
/// never closed still runs to the end of the prompt: a stored first prompt
/// is cut at 200 characters, and a task notification is longer than that.
/// Any other harness-shaped tag (`transcript::is_harness_tag`) counts only
/// when its block is closed, so `<my-widget> renders blank` stays a prompt.
///
/// The list is what 600 local transcripts opened user turns with
/// (2026-09-28): `task-notification` by far the most, then
/// `system-reminder` (usually followed by the person's words), the slash
/// command and `!` bash echoes, and the desktop app's `ci-monitor-event`,
/// `scheduled-task` and `create-pr-command`. `<pasted_content …>` is the
/// person's paste and stays theirs.
pub const HARNESS_TAGS: &[&str] = &[
    "task-notification",
    "system-reminder",
    "ci-monitor-event",
    "scheduled-task",
    "create-pr-command",
    "command-name",
    "command-message",
    "command-args",
    "local-command-stdout",
    "local-command-stderr",
    "local-command-caveat",
    "bash-input",
    "bash-stdout",
    "bash-stderr",
    "user-prompt-submit-hook",
    "teammate-message",
    "ide_opened_file",
    "ide_selection",
];

/// The person's part of `prompt`: the text left once every harness block at
/// its head is taken off, trimmed. `None` when nothing is left — the prompt
/// is Claude Code talking (or it is empty).
pub fn human_part(prompt: &str) -> Option<&str> {
    let mut t = prompt.trim();
    while let Some(rest) = strip_harness_block(t) {
        t = rest.trim_start();
    }
    (!t.is_empty()).then_some(t)
}

/// A non-empty prompt with nothing of a person's in it.
pub fn is_harness(prompt: &str) -> bool {
    !prompt.trim().is_empty() && human_part(prompt).is_none()
}

/// `text` after the harness block it starts with, or `None` when it does
/// not start with one.
fn strip_harness_block(text: &str) -> Option<&str> {
    let rest = text.strip_prefix('<')?;
    let name_end = rest
        .find(|c: char| c == '>' || c.is_whitespace())
        .unwrap_or(rest.len());
    let tag = &rest[..name_end];
    let known = HARNESS_TAGS.contains(&tag);
    if !known && !crate::service::transcript::is_harness_tag(tag) {
        return None;
    }
    let close = format!("</{tag}>");
    match text.find(&close) {
        Some(i) => Some(&text[i + close.len()..]),
        None if known => Some(""),
        None => None,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Shaped like the ones the production hub stored (2026-09-28), cut at
    /// the 200 characters `conversations.first_prompt` keeps.
    fn stored(p: &str) -> String {
        p.chars().take(200).collect()
    }

    #[test]
    fn what_claude_code_submits_itself_is_not_a_persons() {
        for p in [
            stored(
                "<task-notification>\n<task-type>artifact-watch-lifecycle</task-type>\n\
                 <summary>Stopped watching Artifact \"Release notes\": the artifact was deleted.\
                 </summary>\n<status>stopped</status>\n</task-notification>",
            ),
            stored(
                "<task-notification>\n<task-id>afb11347d54b0e640</task-id>\n\
                 <tool-use-id>toolu_01B2ZchuQiWa4VttKoDRjQUd</tool-use-id>\n\
                 <output-file>/tmp/claude-1000/-home-dev-projects-github-com-acme-api/tasks/\
                 afb11347d54b0e640.output</output-file>\n<status>completed</status>\n\
                 <summary>Agent \"Fix PAY-7\" completed</summary>\n</task-notification>",
            ),
            "<system-reminder>\nThe TodoWrite tool hasn't been used recently.\n</system-reminder>"
                .into(),
            "<command-message>review</command-message>\n<command-name>/review</command-name>\n\
             <command-args>PAY-7</command-args>"
                .into(),
            "<local-command-caveat>Caveat: The messages below were generated by the user while \
             running local commands.</local-command-caveat>"
                .into(),
            "<local-command-stdout>Set model to opus</local-command-stdout>".into(),
            "<bash-input>git status</bash-input>".into(),
            "<bash-stdout>On branch main</bash-stdout><bash-stderr></bash-stderr>".into(),
            "  <teammate-message teammate_id=\"lead\">Pick up PAY-7</teammate-message>\n".into(),
            // A long reminder ahead of the person's words: the stored 200
            // characters hold none of them.
            stored(&format!(
                "<system-reminder>\n{}\n</system-reminder>\nfix the PAY-7 retry bug",
                "The task tools haven't been used recently. ".repeat(6)
            )),
            // The desktop app's own, cut at 200 characters.
            stored(&format!(
                "<ci-monitor-event>\nCI finished for pull request #412: 3 checks failed. {}",
                "Read the failing logs and fix them. ".repeat(6)
            )),
            // A known block cut off inside its open tag.
            "<task-notification".into(),
        ] {
            assert!(is_harness(&p), "{p}");
            assert_eq!(human_part(&p), None, "{p}");
        }
    }

    #[test]
    fn a_persons_text_after_the_harness_blocks_is_kept() {
        assert_eq!(
            human_part(
                "<system-reminder>Plan mode is on.</system-reminder>\n\n  fix the PAY-7 retry bug"
            ),
            Some("fix the PAY-7 retry bug")
        );
        assert_eq!(
            human_part(
                "<ide_opened_file>The user opened src/pay.rs</ide_opened_file> why does this panic?"
            ),
            Some("why does this panic?")
        );
    }

    #[test]
    fn a_persons_prompt_stays_a_prompt() {
        for p in [
            "Fix the login bug on mobile",
            "Pozri sa preco padá build na main",
            // A pasted HTML element or config, a tag in the middle.
            "<div>hello</div> is rendered twice, why?",
            "<my_config>on</my_config> — is this valid?",
            "<my-widget> renders blank on Safari",
            "<pasted_content id=\"1\">SELECT * FROM orders",
            "look at this: <task-notification>…</task-notification>",
            "[claude-fleet: message from task #3] done",
        ] {
            assert!(!is_harness(p), "{p}");
            assert_eq!(human_part(p), Some(p.trim()), "{p}");
        }
        assert!(!is_harness(""));
        assert!(!is_harness("   "));
        assert_eq!(human_part("  "), None);
    }
}
