# shellcheck shell=bash
# `ag shims`: one small executable per [alias] entry in $AG_BIN_DIR
# (~/.local/bin). Unlike a zsh alias, a shim works in tmux panes, in
# `ssh host cmd`, and in claude-fleet's pane command. ag only rewrites or
# deletes files that carry AG_SHIM_MARK.

AG_SHIM_MARK='# generated by ag-shims'

ag_bin_dir() {
  printf '%s\n' "${AG_BIN_DIR:-$HOME/.local/bin}"
}

ag_cmd_shims() {
  local dir name val f rc=0 made=" " cfg
  dir=$(ag_bin_dir)
  mkdir -p "$dir" || ag_die 5 "cannot create $dir"
  case $AG_ROOT in *"'"*) ag_die 5 "ag's path contains a single quote: $AG_ROOT" ;; esac
  cfg=$(ag_config_file)
  # Never treat "no config" as "no aliases": that would delete every shim
  # ag has ever generated instead of leaving them alone.
  [ -r "$cfg" ] || ag_die 5 "cannot read $cfg — create a config first (see: ag help)"
  for name in $(ag_config_keys alias); do
    case $name in
      '' | *[!A-Za-z0-9._-]*) echo "ag: alias '$name': invalid name — skipped" >&2; rc=5; continue ;;
    esac
    if ag_is_harness_ci "$name"; then
      echo "ag: alias '$name' would shadow the $name binary — skipped" >&2; rc=5; continue
    fi
    val=$(ag_config_get alias "$name")
    case $val in
      '' | *[!A-Za-z0-9\ ._=/:@%+-]*) echo "ag: alias '$name': value must be plain words — skipped" >&2; rc=5; continue ;;
    esac
    f=$dir/$name
    if [ -e "$f" ] && ! grep -q "^$AG_SHIM_MARK" "$f" 2>/dev/null; then
      echo "ag: $f exists and was not generated by ag — left alone" >&2; rc=5; continue
    fi
    # shellcheck disable=SC2016  # `ag shims` and "$@" are literal text of the generated script
    if ! {
      printf '#!/bin/sh\n%s — edit [alias] in %s, then run `ag shims`\nexec '"'"'%s/ag'"'"' %s "$@"\n' \
        "$AG_SHIM_MARK" "$(ag_config_file)" "$AG_ROOT" "$val" >"$f.tmp" &&
        chmod 755 "$f.tmp" && mv "$f.tmp" "$f"
    }; then
      echo "ag: cannot write $f" >&2; rc=5; continue
    fi
    made="$made$name "
  done
  for f in "$dir"/*; do
    [ -f "$f" ] || continue
    grep -q "^$AG_SHIM_MARK" "$f" 2>/dev/null || continue
    case $made in
      *" $(basename "$f") "*) ;;
      *) rm -f "$f" && echo "ag: removed stale shim $(basename "$f")" ;;
    esac
  done
  return $rc
}
